#Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Vue js
description: Bares Vue js introduction (v.2 and v.3)
